### PR TITLE
Add page for known organizations using Aeryn

### PR DESCRIPTION
**Pull request by SD10**
I just started using this on MessageKit:
https://twitter.com/_SD10_/status/923434393712119808

I thought it would be good to start a list of known organizations who use Aeryn to invite new contributors. I'd like to see this practice more widely adopted one day and I think this list could further encourage people to do so.

### CODE REVIEW

**Review by pedrovereza — COMMENTED** [review]
The approach used by Quick is to have this list in the [wiki](https://github.com/Quick/Quick/wiki/Projects-using-Quick), which, as far as I know, allows anyone to easily add their project without having to submit a PR.

Should we take the same approach?

**Comment by ashfurrow** [comment]
I kind of like it as a text file, but that may only be because I've never really used GitHub wikis and have always used text files 🤷‍♂️ Are wikis editable by non-organization members though?

**Comment by SD10** [comment]
@pedrovereza I kind of like it in a plain text file as well :( To be honest, I don't think we'll receive an overwhelming number of pull requests and I'd like to be notified if someone is using Aeryn.

**Comment by BasThomas** [comment]
I think the people using Aeryn would probably also be able to submit a quick PR. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pedrovereza** [comment]
@ashfurrow @SD10 @BasThomas I personally don't have a clear preference, just wanted to share a possible alternative and get your thoughts on it 👍 

@ashfurrow Yes, non-organization members can edit wikis (this may be configurable). In fact, I just added Harvey to the list of projects using Quick (I'm not a member of Quick)

**Comment by ashfurrow** [comment]
@pedrovereza neat! Okay, let's stick with text files that have been working for Moya so far 👍

**Pull request merged**
