### PR TITLE
Rename Code of Condunct.md to Code of Conduct.md

### PR DESCRIPTION
**Pull request by mrcljx**
(nitpicking me)

### CODE REVIEW

**Comment by ashfurrow** [comment]
Good catch, thanks! Once merged, Aeryn _should_ invite you to the org, fingers crossed 😄

**Comment by ashfurrow** [comment]
Ha, nope 😬 I'll open an issue. Thanks again!

**Comment by ashfurrow** [comment]
I've opened an issue, going to look at the logs and try to re-deliver the hook.

**Comment by ashfurrow** [comment]
Thanks a lot for contributing to Moya! I've invited you to join the Moya GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/Moya/contributors) and feel free to reach out with any questions.

**Comment by ashfurrow** [comment]
Okay, well it looks like it's working now, thanks for being a test subject :) Really gotta get on #1...

**Comment by mrcljx** [comment]
I actually hoped to become a test subject. 👍 Love the idea!

**Pull request merged**
